project:
  type: book

book:
  title: "Learn Crime Mapping with R"
  subtitle: "2025 edition"
  author: Matt Ashby
  search: true
  repo-url: https://github.com/mpjashby/crimemappingbook/
  repo-actions: issue
  output-file: learn_crime_mapping_with_r
  sidebar:
    logo: images/cover_image.png
  sharing:
  - twitter
  - facebook
  - linkedin
  twitter-card: true
  license: Creative Commons Attribution 4.0 International licence
  chapters:
  - index.qmd
  - contents.qmd
  # Week 1: Getting started
  - setup.qmd
  - 01_getting_started/index.qmd
  - 02_your_first_crime_map/index.qmd
  # Week 2: Wrangling data
  - 03_data_wrangling/index.qmd
  - 04_your_second_crime_map/index.qmd
  # Week 3: Mapping patterns
  - 05_code_with_style/index.qmd
  - 06_mapping_crime_patterns/index.qmd
  # Week 4: Map context
  - 07_map_context/index.qmd
  - 08_handling_bugs/index.qmd
  # Week 6: Mapping areas
  - 09_mapping_areas/index.qmd
  - 10_place_data/index.qmd
  # Week 7: Hotspots
  - 11_mapping_hotspots/index.qmd
  - 12_messy_data/index.qmd
  # Week 8: Crime series
  - 13_crime_series/index.qmd
  - 14_writing_reports/index.qmd
  # Week 9: Mapping time
  - 15_no_maps/index.qmd
  - 16_mapping_time/index.qmd
  appendices:
  - appendices/read_functions.qmd
  - appendices/map_checklist.qmd
  - appendices/common_errors.qmd
  - appendices/functions_to_avoid.qmd
  - appendices/handling_errors.qmd
  page-footer:
    center:
    - text: This book is available under a Creative Commons Attribution 4.0 International
        licence
      href: https://creativecommons.org/licenses/by/4.0/

format:
  html:
    theme: cosmo
    toc-depth: 3
    toc-title: In this chapter
    code-copy: true
    code-line-numbers: true
    code-tools: true
    css:
    - css/styles.css
    - include/webex.css
    include-in-header: header.html
    include-after-body: include/webex.js
    resources:
    - "data/*"

filters:
  - line-highlight

