project:
  type: book

book:
  title: "Learn crime mapping with R"
  author: "Matt Ashby"
  date: ""
  search: true
  repo-url: https://github.com/mpjashby/crimemappingbook/
  downloads: [pdf, epub]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - 00_setup/index.qmd
    - 01_getting_started/index.qmd
    - 02_your_first_crime_map/index.qmd
    - 03_data_wrangling/index.qmd

format:
  html:
    theme: cosmo
    css: css/styles.css
    include-in-header:
      - header.html
  pdf:
    documentclass: scrreprt
