project:
  type: book

book:
  title: "Learn crime mapping with R"
  author: "Matt Ashby"
  date: ""
  search: true
  repo-url: https://github.com/mpjashby/crimemappingbook/
  repo-actions: [issue]
  downloads: [epub]
  output-file: "learn_crime_mapping_with_r"
  sharing: [twitter, facebook, linkedin]
  twitter-card: true
  license: "Creative Commons Attribution 4.0 International licence"
  chapters:
    - index.qmd
    - 00_setup/index.qmd
    - 01_getting_started/index.qmd
    - 02_your_first_crime_map/index.qmd
    - 03_data_wrangling/index.qmd
    - 04_code_with_style/index.qmd
    - 05_your_second_crime_map/index.qmd
    - 06_map_context/index.qmd
    - 07_handling_bugs/index.qmd
    - 08_projects/index.qmd
    - 09_mapping_areas/index.qmd
    - 10_place_data/index.qmd
    - 11_mapping_hotspots/index.qmd
    - 12_messy_data/index.qmd
    - 13_crime_series/index.qmd
    - 14_writing_reports/index.qmd
    - 15_no_maps/index.qmd
  appendices:
    - appendices/read_functions.qmd
    - appendices/common_errors.qmd
  page-footer:
    center:
      - text: "This book is available under a Creative Commons Attribution 4.0 International licence"
        href: https://creativecommons.org/licenses/by/4.0/

format:
  html:
    theme: cosmo
    toc-depth: 2
    toc-title: "In this chapter"
    toc-location: left
    code-line-numbers: true
    code-link: true
    css: css/styles.css
    include-in-header:
      - header.html

