project:
  type: book

lang: en-GB

book:
  title: "Learn Crime Mapping with R"
  subtitle: "2026 edition"
  author: Matt Ashby
  description: |
    An introductory textbook on using R to understand and visualise
    spatial and spatio-temporal patterns of crime.
  llms-txt: true
  search:
    location: sidebar
    type: overlay
    show-item-context: tree
  site-url: https://books.lesscrime.info/learncrimemapping/
  repo-branch: main
  repo-actions: [issue]
  issue-url: https://github.com/mpjashby/crimemappingbook/issues/new
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  output-file: learn_crime_mapping_with_r
  sidebar:
    logo: images/cover_image.png
    logo-alt: "Cover of Learn Crime Mapping with R"
    logo-href: index.qmd
    collapse-level: 1
  sharing:
  - twitter
  - facebook
  - linkedin
  open-graph: true
  twitter-card: true
  license: CC BY
  chapters:
  - index.qmd
  - contents.qmd
  # Week 1: Getting started and loading data
  - setup.qmd
  - 01_getting_started/index.qmd
  - 02_your_first_crime_map/index.qmd
  - 03_data_wrangling/index.qmd
  # Week 2: Transforming data and making a second map
  - 04_transforming_data/index.qmd
  - 05_your_second_crime_map/index.qmd
  # Week 3: Improving maps
  - 06_mapping_crime_patterns/index.qmd
  - 07_map_context/index.qmd
  # Week 4: Bugs and area maps
  - 08_handling_bugs/index.qmd
  - 09_mapping_areas/index.qmd
  # Week 5: Place data and hotspots
  - 10_place_data/index.qmd
  - 11_mapping_hotspots/index.qmd
  # Week 6: Messy data and crime series
  - 12_messy_data/index.qmd
  - 13_crime_series/index.qmd
  # Week 7: Reports and non-map presentation
  - 14_writing_reports/index.qmd
  - 15_no_maps/index.qmd
  # Week 8: Mapping time
  - 16_mapping_time/index.qmd
  appendices:
  - appendices/read_functions.qmd
  - appendices/map_checklist.qmd
  - appendices/common_errors.qmd
  - appendices/functions_to_avoid.qmd
  - appendices/handling_errors.qmd
  page-footer:
    center:
    - text: This book is available under a Creative Commons Attribution 4.0 International
        licence
      href: https://creativecommons.org/licenses/by/4.0/

format:
  html:
    theme:
      - cosmo
      - css/theme.scss
    grid:
      body-width: 800px
    toc-depth: 3
    toc-title: In this chapter
    code-copy: true
    code-line-numbers: true
    link-external-icon: true
    fig-cap-location: top
    tbl-cap-location: top
    css:
    - css/styles.css
    - include/webex.css
    include-in-header: header.html
    include-after-body: include/webex.js
    resources:
    - "data/*"
    - "resources/example_quarto_report.qmd"
    - "resources/template.R"
    axe:
      standard: wcag22aa
      # output: document
      output: console
filters:
  - diagrams
  - line-highlight

execute:
  freeze: auto
