# Contents {.unnumbered}

This book is divided into 17 chapters, each covering a different topic related to crime mapping with R. Some of the chapters focus on mapping skills, while others focus more on how good coding practice can make your life easier. The chapters build on one another, so the easiest way to go through the book is to work through the chapters in order. But if you already know some R coding, and something about mapping, you might want to jump into a specific chapter to get what you need.

Before you start, make sure you [install the software you need for this book](setup.qmd).


[Chapter 1: Getting Started](01_getting_started/)
: Get started with crime mapping by learning about why putting crime on maps is useful, and get a tour of the RStudio software we will use throughout this course.

[Chapter 2: Your first crime map](02_your_first_crime_map/)
: Quickly walk (or jog) through the process of creating a complete crime map in R.

[Chapter 3: Wrangling data](03_data_wrangling/)
: Learn the building blocks of data analysis: loading, filtering, manipulating and saving data for crime mapping.

[Chapter 4: Your second crime map](04_your_second_crime_map/)
: Walk through each specific stage in the process of creating a crime map.

[Chapter 5: Code with style](05_code_with_style/)
: Learn how to format your code so that it is easier to use, both for you and for others.

[Chapter 6: Mapping crime patterns](06_mapping_crime_patterns/)
: Learn how to use maps to identify patterns of crime in cities.

[Chapter 7: Giving a map context](07_map_context/)
: Learn how to make your maps easier to understand using supporting elements such as titles and legends.

[Chapter 8: Handling bugs in your code](08_handling_bugs/)
: Learn how to find and fix problems with the R code that you write.

[Chapter 9: Mapping area data](09_mapping_areas/)
: Learn how to make thematic (choropleth) maps that use data for areas to accomplish tasks such as mapping crime rates.

[Chapter 10: Using data about places](10_place_data/)
: Learn how to find and use additional spatial data to improve your crime maps, for example by adding the locations of local facilities that might be important in generating patterns of crime.



::: {.callout-important}
#### Important things you should know

Throughout the book you will see boxes marked with an exclamation mark that contain information that it is particularly important for you to know to avoid common mistakes in writing code or making maps. Pay special attention to these points and remember to ask questions if anything isn't clear.
:::


::: {.callout-tip collapse="true"}
#### Click on this line of text

In this book you will also see lines of text marked by a light-bulb symbol that you can click on to find out more information about a particular issue. This is generally information that you do not need to know to complete a task, but which might be useful in other circumstances or which might answer some questions that you have. You can skip these boxes if you want to, or come back to them later if you have a question.
:::


::: {.callout-quiz .callout}
#### How to use this book

Finally, you will see boxes like this one throughout the book that give you the opportunity to check your understanding of a particular section of that chapter. Sometimes this will be in the form of a multiple-choice question, and sometimes you'll be asked to write some code in the R Console. You will always be able to check if your answers are correct.
:::
