# Welcome! {.unnumbered}

**This book will give you the knowledge and skills to effectively communicate information about crime and related topics using maps. We will cover the principles of analysing geographic information and the strengths and weaknesses of different maps for communicating it.**



## Who is this book for?

This book is for you if you are:

  1. Someone who wants to learn how to understand patterns of crime using maps and related forms of data analysis.
  2. Someone who already knows how to map crimes and would like to learn how to programme in a familiar context.



## Why use this book?

There are several books available for learning crime mapping. The advantages of using this book are that:

  * It teaches up-to-date crime mapping techniques. Some of the most-popular books on crime mapping were written over a decade ago and do not reflect substantial developments in the field since then.
  * It teaches crime mapping using exclusively free software (R and RStudio). Some other books teach crime mapping in expensive proprietary software that most people who need to make crime maps do not have access to.
  * It is an online book, so includes videos to introduce theoretical concepts and walk you through the process of creating different maps.
  * It uses examples from across the world, so it is not only useful to readers from one country.
  * It's completely free to read and redistribute!
  
  

## Why learn crime mapping in R?

We could make crime maps in several different apps. This includes commercial geographic information systems such as ArcGIS or MapInfo, free software such as QGIS, and data analysis programmes such as Tableau. So why learn crime mapping in a programming language like R?

There are several reasons:

  * Making maps using a programming language makes your work much more efficient, especially if (as is common in crime analysis) you need to produce similar maps periodically using updated data, or need to produce multiple similar maps for different areas or crime types.
  * R is free. This can be important for people working in agencies with very limited budgets for software for data analysis.
  * R has extensive mapping capabilities, supported by a large team of friendly experts who provide online support.
  * R is good for other types of data analysis, so everything you learn here can be used for analysing crime data using techniques that are unrelated to maps.

Learning a programming language like R involves a little extra work at the start, but this book is written to make this as easy as possibly by gently introducing you to programming ideas a little at a time. Once you've got started, you'll find mapping crime in this way makes it much easier to advance further in the future.



## How to use this book

There are two ways to use this book. 

  1. You can read it as you would any other technical how-to book, by reading through each
     chapter and working through each exercise in RStudio on your computer or online.
  2. You can work through each chapter as an _interactive tutorial_ in RStudio, getting 
     immediate feedback on each exercise. The interactive tutorials also include quizzes to
     help you check your understanding.

If you want to use the interactive tutorials, there are a few extra set-up steps to work
through at the bottom of this page. They will only take a few minutes.

**I recommend using the interactive tutorials if you can.** The interactive tutorials are
used for teaching crime mapping to [BSc Crime and Security Science](https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/crime-and-security-science-bsc) students at [University College London](https://www.ucl.ac.uk/) so they have been tested by hundreds of people learning crime mapping before you.

