brand: _brand.yml
project:
  type: default
  render:
    - "*/index.qmd"
lang: en-GB
format:
  revealjs:
    theme: [simple, brand, ucl-presentation.scss]
    css: fonts.css
    auto-stretch: true
    code-line-numbers: true
    embed-resources: true
    height: 810
    width: 1440
    incremental: true
    margin: 0.08
    slide-number: true
    transition: fade
    background-transition: fade
from: markdown+emoji
