---
title: "[replace this text with the title of your report]"
author: "Candidate number"
date: today
date-format: "D MMMM YYYY"
format:
  html:
    embed-resources: true
execute:
  echo: false
---


```{r}
#| label: setup
#| include: false

# PREPARE ----------------------------------------------------------------------

## Load packages ----
# Use pacman to load *all* the packages you need for this script here. Do not
# load packages anywhere else in the script. Do not load packages that are not
# needed to run your code.


## Load and clean data ----
# Load all the data you will need here. If the data cannot be downloaded
# directly from a URL, make sure include the code needed to download the file to
# a local file first, then load the data from there. In this section you should
# also do any necessary initial cleaning of the data, e.g. to clean the column
# names.

```

```{r}
#| label: wrangle
# WRANGLE ----------------------------------------------------------------------

# Do any other wrangling of the data that is required before you create one or
# more maps. If several different types of data wrangling are required, use
# header comments (like the line 'Load packages', above) to keep this section
# organised.

```


[Write the text of your report here. This should include the code needed to produce any maps, charts and/or tables you want to include in your report.]


```{r}
#| label: gen-ai-declaration
# GENERATIVE AI DECLARATION ----------------------------------------------------
# Place the appropriate generative AI declaration here.
```
