---
title: "Medellín homicides map"
author: "John Smith"
date: "today"
format:
  html:
    embed-resources: true
    fig-cap-location: top
execute:
  echo: false
---

```{r}
#| label: setup
#| include: false

# Load packages
pacman::p_load(ggspatial, here, httr2, sf, sfhotspot, tidyverse)

# Download the original data into the project
request(
  "https://mpjashby.github.io/crimemappingdata/medellin_homicides.csv"
) |>
  req_perform(path = here("data", "raw", "medellin_homicides.csv"))

request(
  "https://mpjashby.github.io/crimemappingdata/medellin_comunas.gpkg"
) |>
  req_perform(path = here("data", "raw", "medellin_comunas.gpkg"))

# Load homicide data from the local copy
medellin_homicides <- here("data", "raw", "medellin_homicides.csv") |>
  read_csv2() |>
  drop_na(longitud, latitud) |>
  st_as_sf(coords = c("longitud", "latitud"), crs = "EPSG:4326")

medellin_boundary <- here("data", "raw", "medellin_comunas.gpkg") |>
  read_sf() |>
  janitor::clean_names() |>
  st_transform("EPSG:3115")
```

```{r}
#| label: calculate-density
#| include: false

# Calculate crime density
medellin_homicide_density <- medellin_homicides |>
  st_transform("EPSG:3115") |>
  # `hotspot_kde()` prints progress messages by default, but `include: false`
  # prevents them from appearing in the finished report
  hotspot_kde(bandwidth_adjust = 0.33, cell_size = 500) |>
  hotspot_clip(medellin_boundary, quiet = TRUE)
```

@fig-homicides shows the density of homicides in Medellín, Colombia, from 2010 to 2019.

```{r}
#| label: fig-homicides
#| fig-cap: "Density of homicides in Medellín, 2010 to 2019"
#| fig-alt: "Street map of Medellín showing estimated homicide density. The highest density is concentrated in the central part of the city."

# Note we don't have to set `#| include: true` for this code chunk, because that
# is the default

# Plot a basic density map
ggplot() +
  annotation_map_tile(type = "cartolight", zoomin = 0, progress = "none") +
  geom_sf(
    aes(fill = kde),
    data = medellin_homicide_density,
    alpha = 0.7,
    colour = NA
  ) +
  geom_sf(data = medellin_boundary, colour = "grey25", fill = NA) +
  scale_fill_distiller(
    breaks = range(pull(medellin_homicide_density, kde)),
    labels = c("low", "high"),
    direction = 1
  ) +
  labs(
    caption = "Homicide data: Alcaldía de Medellín (CC-BY-SA)",
    fill = "homicide\ndensity"
  ) +
  theme_void()
```
