# Prepare edition metadata or assemble a website without rebuilding archived books.
# Run from the repository root: Rscript publishing/prepare_site.R --help
# Functions can also be sourced into a private environment for checks and tests.

publishing_root <- normalizePath(".", winslash = "/", mustWork = TRUE)
editions_start <- "<!-- book-editions:start -->"
editions_end <- "<!-- book-editions:end -->"

publishing_fail <- function(...) stop(paste0(...), call. = FALSE)

require_publishing_packages <- function(packages) {
  for (package in packages) {
    if (!requireNamespace(package, quietly = TRUE)) {
      publishing_fail("Missing R package '", package,
                      "'. Install with install.packages(\"", package, "\").")
    }
  }
}

# Preserve original HTML bytes, including embedded JavaScript and widget data.
read_text <- function(path) {
  text <- rawToChar(readBin(path, "raw", n = file.info(path)$size))
  Encoding(text) <- "UTF-8"
  text
}

write_text <- function(text, path) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  writeBin(charToRaw(enc2utf8(text)), path)
}

escape_html <- function(text) {
  for (character in c("&", "<", ">", '"', "'")) {
    replacement <- switch(character, "&" = "&amp;", "<" = "&lt;", ">" = "&gt;",
                          '"' = "&quot;", "'" = "&#x27;")
    text <- gsub(character, replacement, text, fixed = TRUE)
  }
  text
}

escape_regex <- function(text) {
  gsub("([][{}()+*^$|\\\\?.])", "\\\\\\1", text)
}

# Insert literal HTML without treating backslashes or dollar signs as replacements.
insert_before <- function(text, marker, insertion) {
  position <- regexpr(marker, text, fixed = TRUE)[1]
  if (position < 0L) publishing_fail("Cannot locate insertion point: ", marker)
  paste0(substr(text, 1L, position - 1L), insertion, substring(text, position))
}

load_manifest <- function() {
  require_publishing_packages("jsonlite")
  path <- file.path(publishing_root, "publishing/editions.json")
  config <- jsonlite::fromJSON(path, simplifyVector = FALSE)
  if (!is.character(config$base_url) || length(config$base_url) != 1L ||
      !grepl("^https://[^?#]+/$", config$base_url)) {
    publishing_fail("base_url must be an HTTPS URL ending in /")
  }
  if (!config$current %in% names(config$editions)) publishing_fail("Current edition is missing")
  for (year in names(config$editions)) {
    if (!grepl("^20[0-9]{2}$", year)) publishing_fail("Invalid edition year: ", year)
    commit <- config$editions[[year]]$commit
    if (year != config$current &&
        (is.null(commit) || !grepl("^[0-9a-f]{40}$", commit))) {
      publishing_fail("Archive ", year, " needs a full commit hash")
    }
  }
  config
}

edition_links <- function(config, selected = "") {
  links <- vapply(sort(names(config$editions), decreasing = TRUE), function(year) {
    paste0('<a href="', escape_html(paste0(config$base_url, year, "/")), '">',
           year, " edition</a>",
           if (year == config$current) " (current)" else "",
           if (year == selected && year != config$current) " (this edition)" else "")
  }, character(1))
  paste(links, collapse = ", ")
}

include_text <- function(config) {
  paste0("<!-- Generated by publishing/prepare_site.R --metadata. -->\n",
         '::: {.callout-note title="Book editions"}\n',
         "This book is updated annually. Read the ", edition_links(config, config$current),
         ".\n:::\n")
}

style_page <- function(config) {
  base <- config$base_url
  current <- paste0(base, config$current, "/")
  chapters <- c("01_getting_started/" = "Getting started",
                "03_data_wrangling/" = "Loading and selecting data",
                "04_transforming_data/" = "Transforming and summarising data",
                "11_writing_reports/" = "Writing reports in R")
  links <- paste0('<li><a href="', current, names(chapters), '">', chapters, '</a></li>')
  paste0('<!doctype html><html lang="en-GB"><head><meta charset="utf-8">',
         '<meta name="viewport" content="width=device-width, initial-scale=1">',
         '<title>Coding with style — Learn Crime Mapping with R</title>',
         '<style>body{max-width:55rem;margin:2rem auto;padding:0 1rem;font:1.1rem/1.6 system-ui}',
         'a{color:#004080}a:focus-visible{outline:3px solid #004080;outline-offset:3px}</style>',
         '</head><body><main><h1>Coding with style</h1>',
         '<p>The former chapter <strong>Coding with style</strong> has been reorganised. ',
         'Its guidance is now spread across these chapters:</p><ul>', paste(links, collapse = ""),
         '</ul><p>Read the original chapter in the ',
         '<a href="', base, '2025/05_code_with_style/">2025 edition</a> or ',
         '<a href="', base, '2024/04_code_with_style/">2024 edition</a>.</p>',
         '<p><a href="', current, '">Current book home page</a></p></main></body></html>\n')
}

prepare_metadata <- function(config, check = FALSE) {
  path <- file.path(publishing_root, "_quarto.yml")
  original <- read_text(path)
  updated <- sub('(?m)^  subtitle:.*$', paste0('  subtitle: "', config$current, ' edition"'), original, perl = TRUE)
  updated <- sub('(?m)^  site-url:.*$', paste0("  site-url: ", config$base_url, config$current, "/"), updated, perl = TRUE)
  generated <- list("_quarto.yml" = updated,
                    "include/_book-editions.qmd" = include_text(config),
                    "code_with_style.html" = style_page(config))
  for (name in names(generated)) {
    target <- file.path(publishing_root, name)
    if (check) {
      if (!file.exists(target) || read_text(target) != generated[[name]]) {
        publishing_fail("Edition metadata is stale; run Rscript publishing/prepare_site.R --metadata")
      }
    } else {
      write_text(generated[[name]], target)
    }
  }
}

root_htaccess <- function(config) {
  base <- sub("^https://[^/]+", "", config$base_url)
  current <- paste0(base, config$current, "/")
  legacy <- readLines(file.path(publishing_root, ".htaccess"), warn = FALSE)
  rules <- legacy[startsWith(legacy, "RewriteRule ")]
  rules <- vapply(strsplit(rules, "[[:space:]]+"), function(parts) {
    paste0("RewriteRule ", parts[2], " ", current, parts[3], " [R=302,END]")
  }, character(1))
  paste0(paste(c(
    "# Generated from publishing/editions.json. Install at the book website root.",
    "RewriteEngine On", paste0("ErrorDocument 404 ", base, "404.html"),
    "# Do not cache the moving current-edition pointer.",
    "<IfModule mod_headers.c>",
    '  Header always set Cache-Control "no-store" "expr=%{REQUEST_STATUS} == 302"',
    "</IfModule>", "# Explicit years must never fall through to the current edition.",
    "RewriteRule ^[0-9]{4}(?:/|$) - [L]", "RewriteRule ^404\\.html$ - [END]",
    rules, paste0("RewriteRule ^(.*)$ ", current, "$1 [R=302,END]")), collapse = "\n"), "\n")
}

# Download into a temporary file, then retain the complete pinned snapshot.
download_archive <- function(config, year, cache) {
  require_publishing_packages(c("httr2", "digest"))
  commit <- config$editions[[year]]$commit
  dir.create(cache, recursive = TRUE, showWarnings = FALSE)
  path <- file.path(cache, paste0(commit, ".tar.gz"))
  checksum_path <- sub("\\.gz$", ".sha256", path)
  if (!file.exists(path)) {
    url <- paste0("https://codeload.github.com/", config$repository, "/tar.gz/", commit)
    message("Downloading ", year, ": ", url)
    temporary <- tempfile(tmpdir = cache)
    on.exit(unlink(temporary), add = TRUE)
    request <- httr2::request(url) |> httr2::req_timeout(120)
    httr2::req_perform(request, path = temporary)
    if (!file.rename(temporary, path)) publishing_fail("Cannot save archive: ", path)
  }
  checksum <- digest::digest(file = path, algo = "sha256", serialize = FALSE)
  if (file.exists(checksum_path) && trimws(read_text(checksum_path)) != checksum) {
    publishing_fail("Archive checksum mismatch: ", path)
  }
  write_text(paste0(checksum, "\n"), checksum_path)
  list(path = path, checksum = checksum)
}

safe_archive_path <- function(path) {
  !grepl("^(/|[A-Za-z]:|\\\\)", path) &&
    !".." %in% strsplit(gsub("\\\\", "/", path), "/", fixed = TRUE)[[1]]
}

# Inspect paths and entry types before extracting. Reject symbolic and hard links
# so no archive member can cause a later extraction to write outside staging.
extract_book <- function(archive, destination, repairs = list()) {
  require_publishing_packages("fs")
  tar <- Sys.which("tar")
  if (!nzchar(tar)) publishing_fail("A tar executable is required to inspect archive entry types.")
  members <- system2(tar, c("-tzf", shQuote(archive)), stdout = TRUE, stderr = TRUE)
  details <- system2(tar, c("-tvzf", shQuote(archive)), stdout = TRUE, stderr = TRUE)
  if (!is.null(attr(members, "status")) || !is.null(attr(details, "status")) ||
      length(members) != length(details)) publishing_fail("Cannot inspect archive: ", archive)
  source_paths <- sub("^[^/]+/", "", members)
  selected <- grepl("^_book(/|$)", source_paths) |
    source_paths %in% vapply(repairs, function(repair) repair$source, character(1))
  if (any(!vapply(members[selected], safe_archive_path, logical(1)))) publishing_fail("Unsafe archive path")
  if (any(!substr(details[selected], 1L, 1L) %in% c("-", "d"))) {
    publishing_fail("Unsupported archive entry: only regular files and directories are allowed")
  }
  for (repair in repairs) {
    if (!safe_archive_path(repair$target)) publishing_fail("Unsafe archive repair target: ", repair$target)
  }
  temporary <- tempfile("edition-extract-")
  dir.create(temporary)
  on.exit(unlink(temporary, recursive = TRUE), add = TRUE)
  status <- utils::untar(archive, files = members[selected], exdir = temporary, tar = tar)
  if (!identical(status, 0L)) publishing_fail("Cannot extract archive: ", archive)
  prefix <- unique(sub("/.*$", "", members[selected]))
  if (length(prefix) != 1L) publishing_fail("Snapshot must contain one repository directory")
  source <- file.path(temporary, prefix)
  if (!file.exists(file.path(source, "_book/index.html"))) publishing_fail("Snapshot contains no rendered book")
  fs::dir_copy(file.path(source, "_book"), destination)
  for (repair in repairs) {
    original <- file.path(source, repair$source)
    if (!file.exists(original) || dir.exists(original)) publishing_fail("Archive repair source missing: ", repair$source)
    target <- file.path(destination, repair$target)
    dir.create(dirname(target), recursive = TRUE, showWarnings = FALSE)
    fs::file_copy(original, target, overwrite = TRUE)
  }
}

archive_page <- function(text, config, year, relative) {
  header <- '<header\\b[^>]*\\bid="quarto-header"[^>]*>'
  if (!grepl(header, text, perl = TRUE)) return(text)
  text <- gsub("(?s)<!-- book-archive:start -->.*?<!-- book-archive:end -->\\s*", "", text, perl = TRUE)
  text <- gsub(paste0("(?s)", escape_regex(editions_start), ".*?", escape_regex(editions_end), "\\s*"), "", text, perl = TRUE)
  base <- config$base_url
  for (old_base in c(base, sub("https:", "http:", base, fixed = TRUE))) {
    pattern <- paste0(escape_regex(old_base), '(?!20[0-9]{2}(?:/|["\\s?#]|$))')
    text <- gsub(pattern, paste0(base, year, "/"), text, perl = TRUE)
  }
  for (unavailable in config$editions[[year]]$unavailable_downloads) {
    pattern <- paste0('(?s)<a\\b[^>]*href="(?:\\./|\\.\\./)*', escape_regex(unavailable), '"[^>]*>.*?</a>')
    text <- gsub(pattern, "", text, perl = TRUE)
  }
  depth <- length(strsplit(relative, "/", fixed = TRUE)[[1]]) - 1L
  prefix <- paste(rep("../", depth), collapse = "")
  assets <- paste0("<!-- book-archive:start -->\n",
                   '<link rel="stylesheet" href="', prefix, 'archive-notice.css">\n',
                   '<noscript><style>header#quarto-header {position:relative!important; transform:none!important;} ',
                   'body {padding-top:0!important;} .sidebar {position:relative!important; top:auto!important;}</style></noscript>\n',
                   "<!-- book-archive:end -->\n")
  text <- insert_before(text, "</head>", assets)
  notice <- paste0("<!-- book-archive:start -->\n",
                   '<div id="book-archive-notice" role="region" aria-label="Archived book edition">',
                   '<strong>Archived edition:</strong> You are reading the ', year, ' edition of ',
                   '<cite>Learn Crime Mapping with R</cite>. ',
                   '<a href="', escape_html(base), '">Read the current edition</a>.',
                   '</div>\n<!-- book-archive:end -->')
  match <- regexpr(header, text, perl = TRUE)
  position <- as.integer(match) + attr(match, "match.length") - 1L
  text <- paste0(substr(text, 1L, position), notice, substring(text, position + 1L))
  if (relative == "index.html") {
    callout <- paste0(editions_start, '\n<aside id="book-editions" aria-label="Book editions"><p>',
                      '<strong>Book editions</strong><br>This book is updated annually. Read the ',
                      edition_links(config, year), '.</p></aside>\n', editions_end, '\n')
    text <- insert_before(text, '<section id="who-is-this-book-for"', callout)
  }
  text
}

required_current_files <- function() {
  lines <- readLines(file.path(publishing_root, "_quarto.yml"), warn = FALSE)
  chapters <- grep("^\\s+- [^\\s#]+\\.qmd\\s*(?:#.*)?$", lines, value = TRUE, perl = TRUE)
  chapters <- sub("^\\s+- ([^\\s#]+\\.qmd).*$", "\\1", chapters, perl = TRUE)
  c("code_with_style.html", "search.json", "llms.txt", sub("\\.qmd$", ".html", chapters))
}

assemble_site <- function(config, current_book, output, cache, refresh_archives = FALSE) {
  require_publishing_packages(c("fs", "jsonlite"))
  prepare_metadata(config, check = TRUE)
  home_path <- file.path(current_book, "index.html")
  if (!file.exists(home_path)) publishing_fail("Render the current book first: ", current_book)
  home <- read_text(home_path)
  if (!grepl("Book editions", home, fixed = TRUE) ||
      !grepl(paste0(config$base_url, config$current, "/"), home, fixed = TRUE)) {
    publishing_fail("Current render lacks edition navigation or year-specific metadata; render it again")
  }
  required <- required_current_files()
  missing <- required[!file.exists(file.path(current_book, required))]
  if (length(missing)) publishing_fail("Current render is incomplete. Run Rscript generate_llms.R; missing: ", paste(missing, collapse = ", "))
  output <- as.character(fs::path_abs(output))
  if (file.exists(output) && !file.exists(file.path(output, ".edition-site"))) {
    publishing_fail("Refusing to replace an unmarked directory: ", output)
  }
  dir.create(dirname(output), recursive = TRUE, showWarnings = FALSE)
  staging <- tempfile(".edition-site-", tmpdir = dirname(output))
  dir.create(staging)
  on.exit(unlink(staging, recursive = TRUE), add = TRUE)
  # Reuse prepared archives only when their inputs and edition navigation agree.
  archive_state <- list(config = config,
    preparer = unname(tools::md5sum("publishing/prepare_site.R")),
    css = unname(tools::md5sum("publishing/archive-notice.css")))
  state_path <- file.path(output, "archive-state.json")
  previous_state <- if (file.exists(state_path)) jsonlite::read_json(state_path) else NULL
  reuse_archives <- !refresh_archives && identical(previous_state, archive_state)
  previous_provenance <- if (reuse_archives) {
    jsonlite::read_json(file.path(output, "edition-provenance.json"))
  } else list()
  provenance <- list()
  for (year in sort(names(config$editions), decreasing = TRUE)) {
    destination <- file.path(staging, year)
    if (year == config$current) {
      fs::dir_copy(current_book, destination)
      provenance[[year]] <- list(source = "current render",
        git_commit = system2("git", c("rev-parse", "HEAD"), stdout = TRUE),
        working_tree_modified = length(system2("git", c("status", "--porcelain"), stdout = TRUE)) > 0L)
    } else if (reuse_archives && dir.exists(file.path(output, year)) &&
               !is.null(previous_provenance[[year]])) {
      fs::dir_copy(file.path(output, year), destination)
      provenance[[year]] <- previous_provenance[[year]]
      message("Reused archived edition ", year)
      next
    } else {
      archive <- download_archive(config, year, cache)
      edition <- config$editions[[year]]
      repairs <- if (is.null(edition$repairs)) list() else edition$repairs
      extract_book(archive$path, destination, repairs)
      access <- fs::dir_ls(destination, recurse = TRUE, all = TRUE, type = "file")
      unlink(access[basename(access) == ".htaccess"])
      for (page in fs::dir_ls(destination, recurse = TRUE, glob = "*.html")) {
        original <- read_text(page)
        relative <- as.character(fs::path_rel(page, destination))
        updated <- archive_page(original, config, year, relative)
        if (original != updated) write_text(updated, page)
      }
      fs::file_copy(file.path(publishing_root, "publishing/archive-notice.css"),
                    file.path(destination, "archive-notice.css"), overwrite = TRUE)
      provenance[[year]] <- list(commit = edition$commit, snapshot_sha256 = archive$checksum,
        adjustments = c("archive banner", "home-page edition links", "absolute book links"),
        repairs = repairs,
        unavailable_downloads = if (is.null(edition$unavailable_downloads)) list() else edition$unavailable_downloads)
    }
    for (page in fs::dir_ls(destination, recurse = TRUE, glob = "*.html")) {
      text <- read_text(page)
      if (grepl('id="quarto-header"', text, fixed = TRUE)) {
        text <- gsub('<link\\b[^>]*rel="canonical"[^>]*>\\s*', "", text, perl = TRUE)
        canonical <- paste0(config$base_url, year, "/", fs::path_rel(page, destination))
        write_text(insert_before(text, "</head>", paste0('<link rel="canonical" href="', canonical, '">\n')), page)
      }
    }
    junk <- fs::dir_ls(destination, recurse = TRUE, all = TRUE, type = "file")
    unlink(junk[basename(junk) == ".DS_Store"])
    message("Prepared ", year)
  }
  write_text(paste0(jsonlite::toJSON(archive_state, auto_unbox = TRUE, pretty = TRUE), "\n"),
             file.path(staging, "archive-state.json"))
  write_text(root_htaccess(config), file.path(staging, ".htaccess"))
  not_found <- paste0('<!doctype html><html lang="en-GB"><meta charset="utf-8">',
                     '<meta name="viewport" content="width=device-width, initial-scale=1">',
                     '<title>Page not found — Learn Crime Mapping with R</title><main>',
                     '<h1>Page not found</h1><p>This page or book edition is unavailable.</p>',
                     '<p><a href="', escape_html(config$base_url), '">Read the current edition</a>',
                     ' or choose an edition:</p><p>', edition_links(config), '</p></main></html>')
  write_text(not_found, file.path(staging, "404.html"))
  write_text(paste0(jsonlite::toJSON(provenance, auto_unbox = TRUE, pretty = TRUE), "\n"),
             file.path(staging, "edition-provenance.json"))
  write_text("Generated by publishing/prepare_site.R\n", file.path(staging, ".edition-site"))
  if (dir.exists(output)) {
    backup <- paste0(output, ".previous")
    if (file.exists(backup)) publishing_fail("Remove or move the previous generated backup first: ", backup)
    if (!file.rename(output, backup)) publishing_fail("Cannot back up output: ", output)
    if (!file.rename(staging, output)) {
      if (!file.rename(backup, output)) publishing_fail("Cannot activate output or restore backup: ", backup)
      publishing_fail("Cannot activate prepared output: ", output)
    }
    unlink(backup, recursive = TRUE)
  } else if (!file.rename(staging, output)) publishing_fail("Cannot activate prepared output: ", output)
  message("Upload the contents of ", output, " to ", config$base_url)
  invisible(output)
}

# Accept --option value and --option=value, and reject unknown or repeated options.
parse_publishing_args <- function(args, flags, values, defaults = list()) {
  parsed <- defaults
  seen <- character()
  while (length(args)) {
    token <- args[1L]
    args <- args[-1L]
    name <- sub("=.*$", "", token)
    if (name %in% seen) publishing_fail("Specify ", name, " only once.")
    seen <- c(seen, name)
    key <- sub("^--", "", name)
    if (name %in% flags && !grepl("=", token, fixed = TRUE)) {
      parsed[[key]] <- TRUE
    } else if (name %in% values) {
      if (grepl("=", token, fixed = TRUE)) {
        value <- sub("^[^=]+=", "", token)
      } else {
        if (!length(args) || startsWith(args[1L], "--")) publishing_fail("Missing value for ", name)
        value <- args[1L]
        args <- args[-1L]
      }
      if (!nzchar(value)) publishing_fail("Missing value for ", name)
      parsed[[key]] <- value
    } else publishing_fail("Unknown argument: ", token)
  }
  parsed
}

prepare_site_main <- function(args = commandArgs(trailingOnly = TRUE)) {
  options <- parse_publishing_args(args, c("--metadata", "--check-metadata", "--refresh-archives", "--help"),
    c("--current-book", "--output", "--cache"),
    list("current-book" = "_book", output = "_site", cache = "publishing/cache"))
  if (isTRUE(options$help)) {
    cat("Usage: Rscript publishing/prepare_site.R [--metadata | --check-metadata]\n",
        "       [--current-book DIR] [--output DIR] [--cache DIR] [--refresh-archives]\n",
        "Run from the book root. Requires jsonlite, fs, httr2, digest and tar.\n", sep = "")
    return(invisible(NULL))
  }
  if (isTRUE(options$metadata) && isTRUE(options[["check-metadata"]])) {
    publishing_fail("Choose either --metadata or --check-metadata.")
  }
  config <- load_manifest()
  if (isTRUE(options$metadata) || isTRUE(options[["check-metadata"]])) {
    prepare_metadata(config, check = isTRUE(options[["check-metadata"]]))
  } else {
    assemble_site(config, options[["current-book"]], options$output, options$cache,
                  refresh_archives = isTRUE(options[["refresh-archives"]]))
  }
}

if (sys.nframe() == 0L) prepare_site_main()
